### PR TITLE
Dev replace below confidence

### PR DESCRIPTION
**Pull request by neeraj9**
replace_below_confidence when lower confidence

The intent is to reset data to some default value when
the confidence level is equal to or below certain value.

Sample usage:

```
    replace_below_confidence($interval, 0.5, 0.0)
```

In the above case 0.5 is the threshold confidence level,
equal to or below which the metric value will be reset to 0.0 (3rd
argument).

@see dalmatinerdb/dalmatinerdb#134

### CODE REVIEW

**Review by Licenser — CHANGES_REQUESTED** [review]
Looks great, a simple test to just prevent regressions would be nice other than that I'll gladly merge and integrate it in the query engine :)

**Comment by neeraj9** [comment]
@Licenser where are the regression tests?

**Comment by Licenser** [comment]
A very short example of tests is here: https://github.com/dalmatinerdb/mmath/blob/76575e7a2ecb3087024e3af54e5509799ac802f4/src/mmath_bin.erl#L142-L151

**Comment by Licenser** [comment]
ping

**Comment by neeraj9** [comment]
pang!
I just could not look at the test cases.

**Comment by neeraj9** [comment]
@Licenser Hope this test is good to go for now.

**Comment by Licenser** [comment]
Looks great!

**Review by Licenser — APPROVED** [review]

**Comment by Licenser** [comment]
I've pulled this into the dev branch of dfe :)

**Comment by neeraj9** [comment]
@Licenser awesome! Thanks

**Comment by neeraj9** [comment]
@Licenser I made a change in dqe as well (see https://github.com/neeraj9/dqe/commit/300365eeb7f21d4f5335682ef9883bc2e27fac1b) to integrate the new function into dfe.
Additionally, which branch of dfe has the change. Basically, I want to get rid of my private branches and build ddb, dfe, px from source.

**Comment by Licenser** [comment]
I've the whole shabang updated already from all the way up to DFE :)

**Comment by neeraj9** [comment]
I can now see it merged to gitlab (https://gitlab.com/Project-FiFo/DalmatinerDB/mmath/commit/c85668bb086b501997a2017383fd49121e41a47e).

The changes to dqe are incomplete. Just so that I can always refer it from here - https://gitlab.com/Project-FiFo/DalmatinerDB/dqe/issues/2

**Pull request merged**
